// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdvzwyrnlhrwibliedsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkdnp3eXJubGhyd2libGllZHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODU2OTcsImV4cCI6MjA1OTA2MTY5N30.UQEm06VvjXEFmcHGaBWvb4dah-IzPYYAV4Xn2oEwCEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);